
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:umayumcha/controllers/inventory_controller.dart';
import 'package:umayumcha/models/product_model.dart';

class ProductFormScreen extends StatelessWidget {
  const ProductFormScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final InventoryController controller = Get.find();
    final TextEditingController nameController = TextEditingController();
    final TextEditingController descriptionController = TextEditingController();
    final TextEditingController skuController = TextEditingController();
    final TextEditingController priceController = TextEditingController();

    return Scaffold(
      appBar: AppBar(title: const Text('Add New Product')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              controller: nameController,
              decoration: const InputDecoration(labelText: 'Product Name'),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: descriptionController,
              decoration: const InputDecoration(labelText: 'Description (Optional)'),
              maxLines: 3,
            ),
            const SizedBox(height: 16),
            TextField(
              controller: skuController,
              decoration: const InputDecoration(labelText: 'SKU (Optional)'),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: priceController,
              decoration: const InputDecoration(labelText: 'Price (Optional)'),
              keyboardType: TextInputType.numberWithOptions(decimal: true),
            ),
            const SizedBox(height: 24),
            Obx(() {
              return controller.isLoading.value
                  ? const CircularProgressIndicator()
                  : ElevatedButton(
                      onPressed: () {
                        final newProduct = Product(
                          id: '', // ID will be generated by Supabase
                          name: nameController.text.trim(),
                          description: descriptionController.text.trim(),
                          sku: skuController.text.trim(),
                          quantity: 0, // Initial quantity is 0, handled by transactions
                          price: double.tryParse(priceController.text.trim()),
                          createdAt: DateTime.now(),
                        );
                        controller.addProduct(newProduct);
                      },
                      child: const Text('Save Product'),
                    );
            }),
          ],
        ),
      ),
    );
  }
}
